version: "3"

services:
    pyrobomotra:
        image: virtualorigami/pyrobomotra:stateless 
        container_name: pyrobomotra
        env_file: example.env
        volumes:
            - ./configuration/pyrobomotra/config.yaml:/pyrobomotra/config.yaml:ro
        networks:
            - "iotstack"
    
    pypersonnelloc:
        image: virtualorigami/pypersonnelloc:stateless 
        container_name: pypersonnelloc
        env_file: example.env
        volumes:
            - ./configuration/pypersonnelloc/config.yaml:/pypersonnelloc/config.yaml:ro
        networks:
            - "iotstack"
    
    pycollisionavoidance:
        image: virtualorigami/pycollisionavoidance:stateless 
        container_name: pycollisionavoidance
        env_file: example.env
        volumes:
            - ./configuration/pycollisionavoidance/config.yaml:/pycollisionavoidance/config.yaml:ro
        networks:
            - "iotstack"
    
volumes:
    redis_data:

networks:
    iotstack:
        external: true
