preset:
  amq: # AMQP Broker Information
    broker: &amq_connect_info
      address: "localhost"
      port: 5672
    credentials: &amq_credential
      username: "admin"
      password: "rabbit"
  redis: &redis_connect_info
    server:
      address: "localhost"
      port: 6379
    credentials:
      password: "rabbit"
  pub_sub:
    - pub_sub_1: &pub_plm
        type: "amq"
        broker: *amq_connect_info
        credential: *amq_credential
        exchange: "plm_walker"
        queue: "plm_walker_rk"
        handler:
    - pub_sub_2: &sub_generator_personnel
        type: "amq"
        broker: *amq_connect_info
        credential: *amq_credential
        exchange: "generator_personnel"
        queue: "generator_personnel_rk"
        handler: "personnel_msg_handler"
    - pub_sub_3: &pub_visual
        type: "amq"
        broker: *amq_connect_info
        credential: *amq_credential
        exchange: "visual"
        queue: "visual_plm_personnel_rk"
        handler:
  attributes:
    rakf:
      rakf_1: &rakf_1
        type: 'rakf'
        track_dimension: 3
        model:
          type: "uwb_imu"     #type can be of   1. "uwb_imu"    2. "uwb"
          coefficient: { x: 1, y: 1, z: 1 }
        error:
          model: { x: 1, y: 1, z: 1 }
          measurement: { x: 1, y: 1, z: 1 }
          state_error_variance: { x: 10, y: 10, z: 10 }
        threshold:
          residual: { x: 1.5, y: 1.5, z: 1.5 } # C (outer circle)
          adaptive: { x: 1, y: 1, z: 1 } # C0 (Inner Circle)
          gamma: { x: 50, y: 50, z: 50 }
        estimator:
          parameter:
            count: 10
        interval: 0.05
      rakf_2: &rakf_2
        type: 'rakf'
        track_dimension: 3
        model:
          type: "uwb"     #type can be of   1. "uwb_imu"    2. "uwb"
          coefficient: { x: 1, y: 1, z: 1 }
        error:
          model: { x: 1, y: 1, z: 1 }
          measurement: { x: 0.5, y: 0.5, z: 0.5 }
          state_error_variance: { x: 1, y: 1, z: 1 }
        threshold:
          residual: { x: 0.5, y: 0.5, z: 0.5 } # C (outer circle)
          adaptive: { x: 0.25, y: 0.25, z: 0.25 } # C0 (Inner Circle)
        estimator:
          parameter:
            count: 10
        interval: 0.1
  protocols:
    protocol_1: &protocol_1
      publishers:
        - *pub_plm
        - *pub_visual
      subscribers:
        - *sub_generator_personnel
localization:
  version: "0.1"
  trackers:
    - algorithm: *rakf_1
      protocol: *protocol_1
      in_mem_db: *redis_connect_info

#    - id: '1'
#      start_position: { x: 120, y: 55, z: 0 }
#      algorithm: *rakf_1
#      protocol: *protocol_1
#      start_position: { x: 30, y: 50, z: 0 }


